---
- name: install and start apache
  hosts: [group name]
  become: yes

  tasks:
        - name: httpd package is present
          yum:
           name: httpd
           state: latest

        - name: httpd is started
          service:
           name: httpd
           state: started
